### ISSUE TITLE
gnome_keyring_lock_all_sync is deprecated

### ISSUE THREAD

**Issue by nikhilramolla** [intika/gnome-keyring-tools#1]
Is there any other way to lock?
I'm compiling on Ubuntu 18.04

**Comment by intika** [comment]
my system is not yet using new version i can not test, will update this when my system get updates to new version... 

secret_service_lock() from libsecret should be used instead... 

Also a dbus call should be possible i will look how to do that and post back 

Links 

https://developer.gnome.org/libsecret/unstable/migrating-locking.

https://people.gnome.org/~stefw/libsecret-docs/SecretService.html#secret-service-lock

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=697896

**Comment by intika** [comment]
there we go here is the command to unlock through dbus... i will update the readme 

`qdbus org.gnome.keyring /org/freedesktop/secrets org.freedesktop.Secret.Service.LockService`
